# Generated by Django 3.2.9 on 2021-11-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmography', '0002_actor_favourite_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(to='filmography.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='actors',
            field=models.ManyToManyField(through='filmography.Favourite', to='filmography.Actor'),
        ),
    ]
