# Generated by Django 3.2.9 on 2021-11-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmography', '0003_auto_20211119_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
