# Generated by Django 3.2.9 on 2021-11-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmography', '0003_auto_20211106_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='is_favourite',
            field=models.BooleanField(),
        ),
    ]
