# Generated by Django 3.2.9 on 2021-11-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmography', '0004_auto_20211122_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_images/'),
        ),
    ]
