# Generated by Django 3.2.9 on 2021-11-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmography', '0004_auto_20211122_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='actoruserrequest',
            name='status',
            field=models.CharField(choices=[('p', 'W kolejce'), ('e', 'Błąd'), ('d', 'Pobrano')], default='p', max_length=1),
        ),
    ]
