# Generated by Django 3.2.9 on 2021-11-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmography', '0005_actoruserrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='imdb_id',
            field=models.CharField(default=0, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actoruserrequest',
            name='status',
            field=models.CharField(choices=[('p', 'W kolejce'), ('r', 'W trakcie pobierania'), ('e', 'Błąd'), ('d', 'Pobrano')], default='p', max_length=1),
        ),
    ]
