# Generated by Django 3.2.9 on 2021-11-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmography', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='imdb_id',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actoruserrequest',
            name='status',
            field=models.CharField(choices=[('p', 'W kolejce'), ('r', 'W trakcie pobierania'), ('e', 'Błąd'), ('d', 'Pobrano')], default='p', max_length=1),
        ),
    ]
