# Generated by Django 3.2.9 on 2021-12-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmography', '0008_movierequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_api_counter',
            field=models.IntegerField(default=0),
        ),
    ]
