# Generated by Django 3.2.9 on 2021-12-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmography', '0009_userprofile_daily_api_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='actoruser',
            name='phrase',
            field=models.CharField(default='brak', max_length=64),
            preserve_default=False,
        ),
    ]
